### ISSUE TITLE
Installation Issue - Catalog display plugin

### ISSUE THREAD

**Issue by sunnysrivastav15** [overvis/opencart-plugins#14]
Catalog display plugin- Getting error while uploading extension via opencart installer.

"Forbidden
Forbidden
<!DOCTYPE HTML PUBLIC “-//IETF//DTD HTML 2.0//EN”>
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don’t have permission to access this resource.</P>
<p>Additiionaly, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.</P>
</body></html>"

**Comment by qwerty541** [comment]
You need to check Apache/Nginx error logs for reason why.
