### ISSUE TITLE
2 bugfixes for Simple-cookie-policy-notice

### ISSUE THREAD

**Issue by mhcwebdesign** [overvis/opencart-plugins#15]
The following bugs should be fixed for **Simple-cookie-policy-notice**:

File admin/controller/extension/module/cookie_notice.php line 62:

Replace
`                    'module_id' => $this->request->get['module_id'] ?? null`
with
`                    'module_id' => empty($this->request->get['module_id']) ? null : $this->request->get['module_id']`

File catalog/controller/extension/module/cookie_notice.php line 7:

Replace
`        $data['cookie_consent'] = $this->request->cookie['cookie_consent'] ?? false;`
with
`        $data['cookie_consent'] = empty($this->request->cookie['cookie_consent']) ? false : true;`

Otherwise, it will complain on some PHP versions!

Juergen

**Comment by qwerty541** [comment]
Thanks, but it’s unlikely to be called a bug, it’s rather an enhancement for compatibility with earlier php versions.
