### ISSUE TITLE
Issue with Catalog display plugin

### ISSUE THREAD

**Issue by Vladimir-N-Marchenko** [overvis/opencart-plugins#16]
**Name of plugin**
Catalog display plugin

**Describe the bug**
После добавления,в Товаре не появляется переключатель "Show in catalog"

**To Reproduce**
1. Find the product you want to show in the catalog:
Catalog -> Products -> *Product name* -> Edit
2. Go to Data section.
3. Switch option Show in catalog to Yes.

**Server / Test environment (please complete the following information):**
 - OpenCart version 3.0.3.2(rs.2) Русская сборка
 - PHP version 7.3.15
 - Chrome

**Comment by qwerty541** [comment]
Всякий раз, когда вы включаете/отключаете или удаляете модификацию, вам нужно нажать кнопку обновления, чтобы перестроить кэш ваших модификаций. Кнопка находится по пути: Dashboard -> Extensions -> Modifications.

![123](https://user-images.githubusercontent.com/53787217/81217738-c85c5b00-8fe5-11ea-82ef-6183cc06e492.jpg)

**Comment by Vladimir-N-Marchenko** [comment]
Здравствуйте, Александр. 
Я выполняю этот шаг, каждый раз после установки. 
По вашему совету, выполнил его еще раз, и очистил кэш Админ панели.
Панель состояния — Иконка в правом углу — Очистить кэш темы.
После этого переключатель появился. 
Огромное вам спасибо.
Оставлю отзыв.
Удачи в ваших делах и новых разработках.
 
  
>Четверг, 7 мая 2020, 2:07 +07:00 от Alexandr <notifications@github.com>:
> 
>Всякий раз, когда вы включаете/отключаете или удаляете модификацию, вам нужно нажать кнопку обновления, чтобы перестроить кэш ваших модификаций. Кнопка находится по пути: Dashboard -> Extensions -> Modifications.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
С уважением, Владимир Марченко.
тел. +7 913 270 3838

**Comment by Vladimir-N-Marchenko** [comment]
После выполнения рекомендаций, появился пункт Show in catalog.
Плагин работает как заявлено в описании. 
Автор ответил очень быстро, и дал рекомендации.
Рекомендую.
