### ISSUE TITLE
It doesn't show anything on one installation of two

### ISSUE THREAD

**Issue by svdumitrescu** [overvis/opencart-plugins#19]
Nice and simple. One issue though. I have two almost identical installations of OC 3.0.3.7, one on a subdomain and the other on the main domain. On the subdomain the plugin worked like charm at the first try. On the main domain it did not show anything, even if I followed the exact same steps. Tried all possible combinations of refreshing theme, deleting browser's cache, to no avail, it does not show at all, whatever I do. Any idea, please?

**Comment by qwerty541** [comment]
Let's first determine if I understand your problem correctly. You are on the page, the screenshot of which I will attach below, you submit a file with the `.ocmod.zip` extension and nothing happens, right?

![image](https://user-images.githubusercontent.com/53787217/127794143-6f6e3335-3819-4602-8dfb-d2bc0b1f2ddf.png)

If I understand your problem correctly, then I recommend adding the following lines into beginning of file `/OPENCART-ROOT/admin/index.php` and try submit form one more time. Most likely you should see an error. Do not forget to remove these lines from the file later.

```php
ini_set('display_errors', '1');
error_reporting(E_ALL);
```

If the previous advice did not help you, you can try to look for an error in the logs `/OPENCART-STORAGE/logs/*.log`

**Comment by qwerty541** [comment]
As a last resort, if you cannot install the plugin using the form in the admin panel, you can install the plugin manually by moving the plugin files to the desired locations. Read more about this in the plugin documentation in the section [installation by FTP](https://github.com/overvis/opencart-plugins/tree/master/Simple-cookie-policy-notice#installation-by-ftp).

**Comment by svdumitrescu** [comment]
Hi. Thanks for answering. No, they both installed succesfully. So there are two almost identical installations, one on the main domain, it's a project I develop, still trying to figure out the best direction, and another installation on a subdomain, a demo for a potential customer. On the subdomain it worked at first try, on the main domain no way. You may look on the following links:
https://demo.magazine-romanesti.eu/
https://www.magazine-romanesti.eu/
Best regards
     On Monday, August 2, 2021, 05:06:27 AM GMT+3, Alexandr ***@***.***> wrote:  
 
 


Let's first determine if I understand your problem correctly. You are on the page, the screenshot of which I will attach below, you submit a file with the .ocmod.zip extension and nothing happens, right?



If I understand your problem correctly, then I recommend adding the following lines into beginning of file /OPENCART-ROOT/admin/index.php and try submit form one more time. Most likely you should see an error. Do not forget to remove these lines from the file later.
ini_set('display_errors', '1');error_reporting(E_ALL);
If the previous advice did not help you, you can try to look for an error in the logs /OPENCART-STORAGE/logs/*.log

**Comment by qwerty541** [comment]
> Hi. Thanks for answering. No, they both installed succesfully. So there are two almost identical installations, one on the main domain, it's a project I develop, still trying to figure out the best direction, and another installation on a subdomain, a demo for a potential customer. On the subdomain it worked at first try, on the main domain no way. You may look on the following links: https://demo.magazine-romanesti.eu/ https://www.magazine-romanesti.eu/ Best regards On Monday, August 2, 2021, 05:06:27 AM GMT+3, Alexandr ***@***.***> wrote: Let's first determine if I understand your problem correctly. You are on the page, the screenshot of which I will attach below, you submit a file with the .ocmod.zip extension and nothing happens, right? If I understand your problem correctly, then I recommend adding the following lines into beginning of file /OPENCART-ROOT/admin/index.php and try submit form one more time. Most likely you should see an error. Do not forget to remove these lines from the file later. ini_set('display_errors', '1');error_reporting(E_ALL); If the previous advice did not help you, you can try to look for an error in the logs /OPENCART-STORAGE/logs/*.log — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

The fact that your interface says that the plugin has been installed successfully does not mean anything at all. If after installation you cannot find the plugin along the path `Extensions -> Extensions -> Modules -> Simple cookie policy notice` in admin panel it means that plugin installation failed. At the moment, your task is to get some kind of feedback from the system, for example, an error text. Without this, you will not understand what the problem is, and accordingly you will not be able to fix anything. The two methods that I described in previous posts will just help you do this. In addition to the previously proposed methods, I can suggest that you check if you have the necessary `Access Permission` and `Modify Permission` in admin panel along the path `System -> User -> User Groups -> Administrator (Or what group do you belong to?)`

**Comment by svdumitrescu** [comment]
@qwerty541 :: I'll follow your instructions, check the error logs. But why can be different (the plugin's behavior) between two exact same installations of OC? One on the main domain and another on the subdomain. I didn't take the time to look over your scripts, saw the controller but I just quickly got over the model, I was thinking you might inserted some protection so that the plugin won't work more than one instance on one domain. As of permissions and privileges, again there are two exact same installations of OC, I'm the only Super User on both.

**Comment by qwerty541** [comment]
> @qwerty541 :: I'll follow your instructions, check the error logs. But why can be different (the plugin's behavior) between two exact same installations of OC? One on the main domain and another on the subdomain. I didn't take the time to look over your scripts, saw the controller but I just quickly got over the model, I was thinking you might inserted some protection so that the plugin won't work more than one instance on one domain. As of permissions and privileges, again there are two exact same installations of OC, I'm the only Super User on both.

Hey! How are you doing? Did you manage to solve the problem? There is no protection against multiple plugin instances running on the same domain.
